### ISSUE TITLE
Address does not support IPv6 address

### ISSUE THREAD

**Issue by teran-mckinney** [maxcnunes/waitforit#20]
I can't get `-address` to accept an IPv6 address with or without brackets. `-host` is fine.

**Comment by maxcnunes** [comment]
It could be because of [the regex we use to resolve the address info](https://github.com/maxcnunes/waitforit/blob/master/connection.go#L8). It has just been updated to use a new rule, could you check if that works for you on v2.2.1?

**Comment by teran-mckinney** [comment]
Hey!

Thanks for looking into this. No such luck.

```
$ /var/tmp/go/bin/waitforit -address http://[2001:41d0:8:6a52:298:2dff:fef3:8ce1]
2018/08/31 12:47:40 Invalid connection main.Config{Host:"", Port:80, Address:"http://[2001:41d0:8:6a52:298:2dff:fef3:8ce1]", Timeout:10, Retry:500}
$ /var/tmp/go/bin/waitforit -address http://2001:41d0:8:6a52:298:2dff:fef3:8ce1
2018/08/31 12:47:45 Invalid connection main.Config{Host:"", Port:80, Address:"http://2001:41d0:8:6a52:298:2dff:fef3:8ce1", Timeout:10, Retry:500}
$ /var/tmp/go/bin/waitforit -address tcp://[2001:41d0:8:6a52:298:2dff:fef3:8ce1]:22
2018/08/31 12:47:48 Invalid connection main.Config{Host:"", Port:80, Address:"tcp://[2001:41d0:8:6a52:298:2dff:fef3:8ce1]:22", Timeout:10, Retry:500}
```

**Comment by maxcnunes** [comment]
Thanks for checking it out. I have just fixed it on https://github.com/maxcnunes/waitforit/commit/1de194e5575614f89bf4d40a3eb38205bfb2e6c7 and I will release it later this weekend.
