### ISSUE TITLE
Headers : Authorization: Basic won't work - Authorization:Basic will...

### ISSUE THREAD

**Issue by nsteinmetz** [maxcnunes/waitforit#24]
Hi @maxcnunes 

Testing the auth headers, I had a small issue:

```
./waitforit -address=https://url.bigocrp.com:443 -header "Authorization: Basic [REDACTED]" -timeout=60 -debug
2018/09/27 11:09:24 Waiting 60 seconds
2018/09/27 11:09:24 Ping host: url.bigocrp.com:443
2018/09/27 11:09:24 Ping host: url.bigocrp.com:443
2018/09/27 11:09:24 Up: url.bigocrp.com:443
2018/09/27 11:09:24 Ping http address: https://url.bigocrp.com:443
2018/09/27 11:09:24 Adding header Authorization:  Basic [REDARCED]
2018/09/27 11:09:24 Ping http address https://url.bigocrp.com:443 401 Unauthorized
```

I noticed there are 2 spaces between `Authorization` and `Basic` in the debug output. So I changed for a no space version ie `"Authorization:Basic` in the args and it works :

```
./waitforit -address=https://url.bigocrp.com:443 -header "Authorization:Basic [REDACTED]" -timeout=60 -debug
2018/09/27 11:09:41 Waiting 60 seconds
2018/09/27 11:09:41 Ping host: url.bigocrp.com:443
2018/09/27 11:09:41 Ping host: url.bigocrp.com:443
2018/09/27 11:09:41 Up: url.bigocrp.com:443
2018/09/27 11:09:41 Ping http address: https://url.bigocrp.com:443
2018/09/27 11:09:41 Adding header Authorization: Basic [REDACTED]
2018/09/27 11:10:01 Ping http address https://url.bigocrp.com:443 200 OK
```

I quickly reviewed the code and did not find where the issue may be.

Or it's only the doc to update ?

Thanks,
Nicolas

**Comment by maxcnunes** [comment]
Hi @nsteinmetz, 

Good catch. I believe we have two options here:
* document the header arguments shouldn't have whitespaces around the colon character
* apply trim to the income values here https://github.com/maxcnunes/waitforit/blob/master/main.go#L102

**Comment by nsteinmetz** [comment]
Hi,

2nd option seems more logical/relevant for me - I will try to propose a fix this afternoon.

Nicolas

**Comment by nsteinmetz** [comment]
why not just do (naive approach)for line 98 :

```
				result := strings.SplitN(v, ": ", 2)
```

As triming spaces is not really an option as we need to keep the space between Basic and the based64 encoded credentials.

**Comment by nsteinmetz** [comment]
or 

```
				headers[result[0]] = strings.TrimLeft(result[1], " ")
```

What whould you prefer ?

**Comment by nsteinmetz** [comment]
I suggested both then :-)

**Comment by maxcnunes** [comment]
The second option seems better since it allows people with or without the prefix white space.
