### ISSUE TITLE
For http(s) address, port is now required

### ISSUE THREAD

**Issue by nsteinmetz** [maxcnunes/waitforit#26]
Hi,

Small regression for https urls - it's now mandatory to specify the port (443) to the url whereas it worked without so far.

```
./waitforit -address=https://www.google.fr -debug                                                                                                                                                            
2018/09/28 08:45:18 Waiting 10 seconds
2018/09/28 08:45:18 Ping host: www.google.fr
2018/09/28 08:45:18 Ping host: www.google.fr
2018/09/28 08:45:18 Down: www.google.fr
2018/09/28 08:45:18 dial tcp: address www.google.fr: missing port in address
```

With port defined:

```
./waitforit -address=https://www.google.fr:443 -debug                                                                                                                                             
2018/09/28 08:45:41 Waiting 10 seconds
2018/09/28 08:45:41 Ping host: www.google.fr:443
2018/09/28 08:45:41 Ping host: www.google.fr:443
2018/09/28 08:45:41 Up: www.google.fr:443
2018/09/28 08:45:41 Ping http address: https://www.google.fr:443
2018/09/28 08:45:41 Ping http address https://www.google.fr:443 200 OK
```

Will investigate later today.

Nicolas

**Comment by nsteinmetz** [comment]
Think it's between here:

https://github.com/maxcnunes/waitforit/blob/master/connection.go#L59-L67

and here:

https://github.com/maxcnunes/waitforit/blob/master/network.go#L97

I tend to think that `Host` is overwritten - should it be splitted into two variables as you may want to ping `Host` one one side but do a http call on `<scheme>/<host>:<port>`

In `valid_config.json` for tests, you should add also:

```
    {
      "address": "http://google.com",
      "timeout": 40
    },    
    {
      "address": "https://google.com",
      "timeout": 40
    }, 
```

**Comment by nsteinmetz** [comment]
hi @maxcnunes,

Any idea on this ? Too newbie in go to be sure on this.

Thanks,
Nicolas

**Comment by maxcnunes** [comment]
hey @nsteinmetz, sorry for the delay, I was quite busy lately. That commit I just pushed should fix it.

**Comment by nsteinmetz** [comment]
@maxcnunes no problem, it happens.

Will test it soon :)

Thanks !

**Comment by nsteinmetz** [comment]
Cool, it works - thanks !
